spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_db
    username: root
    password: "Dastanchik7"  # Или ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

jwt:
  secret: "5491a689-edec-40cd-b615-cd0fde490c11"
  expirationMs: 3600000         # 1 час
  refreshExpirationMs: 86400000 # 1 день

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ТВОЙ_GOOGLE_CLIENT_ID
              client-secret: ТВОЙ_GOOGLE_CLIENT_SECRET
              scope:
                - openid
                - profile
                - email
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub

