spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_db
    username: root
    password: "Dastanchik7"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 845863838629-kvmvu7d0fpn512j6f9sh7q6b15v5akru.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: "o9tB8T1zJmxQX+TWdj5w1GpE0yBr7hE6aJuM9HzG7IA="
  expirationMs: 3600000
  refreshExpirationMs: 86400000
